// ===========================================================================
// plan-data.ts — the DATA for plan.html (day-by-day, all options) + rank.html.
//
// What this is: every candidate activity for the trip, verified Jul 17 2026
//   (73 researched → these keepers), each with WHAT-IT-IS one-liner, expanded
//   detail, and — Allison's rule — DISTANCE ALWAYS (🚗 from the day's base).
// Why it exists: the local slideshow became a shared site so Avital can click,
//   expand, comment (austria_notes) and rank (austria_2026_state).
// Decided: Shabbat = Bad Goisern self-catered · Friday = Jewish/remembrance
//   day (4 routes, her pick) · nothing else locked — every day is a menu.
// Next: their picks land in rank.html → Claude reads state between sessions.
// Links: BOOKINGS in second-brain/projects/austria-2026/BOOKINGS.md ·
//   research: second-brain session 2026-07-17 · photos: Wikimedia Commons.
// ===========================================================================

export type Difficulty = 'flat' | 'easy' | 'moderate';

export interface Activity {
  id: string;
  name: string;
  emoji: string;
  what: string; // one-line "what this actually is"
  more: string; // expanded detail shown on click
  drive: string; // ALWAYS present — 🚗 time (+km where verified) from the named base
  duration: string;
  difficulty: Difficulty;
  chips: string[];
  photo: string;
  sunset?: boolean;
  swim?: boolean;
  star?: boolean; // lifetime-memory candidate
  jewish?: boolean;
  maps: string; // Google Maps destination link
}

const P = (f: string): string =>
  `https://commons.wikimedia.org/wiki/Special:FilePath/${f}?width=900`;
const G = (q: string): string =>
  `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`;

export const ACTIVITIES: Activity[] = [
  // ---- Friday / Jewish + remembrance -------------------------------------
  {
    id: 'mauthausen',
    name: 'Mauthausen Memorial',
    emoji: '🕯️',
    what: 'The main Nazi concentration camp in Austria (1938–45, ~90,000 murdered) — today the national memorial.',
    more: 'The camp, the quarry with the “Stairs of Death,” and the Room of Names. Free entry, excellent audio guides, open daily 09:00–17:30 (last entry 16:45). Emotionally the heaviest visit of the trip — plan ~3 hours and a quiet drive after. Mostly outdoor walking on uneven ground, no climbing required.',
    drive: '🚗 1h45 · 154 km from Salzburg airport (Fri) · 1h40 · 131 km back to Bad Goisern',
    duration: '~3h on site',
    difficulty: 'easy',
    chips: ['free entry', 'open Fri 09:00–17:30', 'the major one'],
    photo: P('Wiener%20Graben%20quarry%20by%20Stefanie%20J%20Steindl%20012.jpg'),
    jewish: true,
    star: true,
    maps: G('Mauthausen Memorial'),
  },
  {
    id: 'ebensee',
    name: 'Ebensee memorial + tunnels',
    emoji: '🕯️',
    what: 'A Mauthausen sub-camp by the Traunsee — prisoners dug vast tunnels for Nazi arms production; thousands died.',
    more: 'You walk into the actual Gedenkstollen (memorial tunnel) — 8°C inside even in July, bring layers. Exhibition inside the tunnel + the camp cemetery and the surviving camp gate outside (outdoor parts free, always open). Tunnel + museum ~€5, open Tue–Sun 10:00–17:00, closed Mondays. Basically local to the Bad Goisern base.',
    drive: '🚗 25 min · 27 km from Bad Goisern (1h10 · 80 km from Salzburg airport)',
    duration: '~2h',
    difficulty: 'flat',
    chips: ['€5', 'Tue–Sun 10–17', '8°C inside — layers'],
    photo: P('EbenseeZeitgeschichteMuseum.jpg'),
    jewish: true,
    maps: G('KZ-Gedenkstätte Ebensee'),
  },
  {
    id: 'salzburg-jewish-walk',
    name: 'Salzburg remembrance walk',
    emoji: '✡️',
    what: 'A flat self-guided loop through Jewish Salzburg — 800 years of presence, destruction, and rebuilding.',
    more: 'Judengasse (the medieval Jewish lane, synagogue at #15 in 1370) → Marko Feingold bridge over the Salzach (named for the four-camp survivor who rebuilt the community, lived to 106) → Stolpersteine brass memorial stones in the pavement (500+ across the city; dense cluster around Linzergasse) → the synagogue at Lasserstraße 8, burned on Kristallnacht 1938, rebuilt, still a living shul (~100 members). To go INSIDE the synagogue: email office@ikg-salzburg.at in advance — no walk-ins, security. All outdoor parts free, at your pace.',
    drive:
      '🚗 18 min from Salzburg airport to Altstadt parking · then on foot · 1h07 · 76 km on to Bad Goisern',
    duration: '~2.5–3h walking',
    difficulty: 'flat',
    chips: ['free', 'self-guided', 'synagogue inside = email ahead'],
    photo: P('Salzburg%20Stolperstein%20Linzer%20Gasse%2038.jpg'),
    jewish: true,
    maps: G('Judengasse Salzburg'),
  },
  {
    id: 'jewish-ischl',
    name: '“Jewish Ischl” walk',
    emoji: '✡️',
    what: 'Bad Ischl — the imperial spa town — had a real Jewish community; the Pins of Remembrance route marks its story.',
    more: 'Oversized memorial “pins” mark the Nazi-era sites of Jewish Bad Ischl (maps at the tourist office). The town itself is the old imperial summer capital — Kaiservilla, riverside promenade, famous café culture. A gentle add-on to any day that passes through — and your grocery stop is here anyway.',
    drive:
      '🚗 15 min · 12 km from Bad Goisern · 29 min · 24 km from Gosau · en-route stop on the Tue Zell→Gosau move',
    duration: '~1h',
    difficulty: 'flat',
    chips: ['free', 'on your route', 'pairs with groceries'],
    photo: P('Kaiservilla%20Bad%20Ischl.JPG'),
    jewish: true,
    maps: G('Bad Ischl tourist office'),
  },
  {
    id: 'krimml-apc',
    name: 'Krimml Falls + the 1947 exodus path',
    emoji: '✡️',
    what: "Austria's tallest waterfall (380 m) — and the pass where thousands of Jewish survivors crossed the Alps on foot in 1947 toward Eretz Yisrael.",
    more: 'Three tiers of thundering water beside an easy (but uphill) path — walk to the first tier (worth it alone) or as high as feels good and turn back. At the valley head, the Alpine Peace Crossing memorial marks the Krimml Tauern route of the 1947 Bricha exodus: survivors, packs on backs, walking to a ship to Israel. Nature and Jewish memory in the same steps. Mist cools the whole path on a hot day.',
    drive: '🚗 1h10 · 55 km from Zell am See',
    duration: 'half day',
    difficulty: 'easy',
    chips: ['~€11 falls entry', 'easy but uphill', 'meaningful'],
    photo: P('Krimml%2C%20der%20Wasserfall%2C%20Bild%2015.jpg'),
    jewish: true,
    star: true,
    maps: G('Krimml Waterfalls'),
  },

  // ---- Zell am See leg -----------------------------------------------------
  {
    id: 'kitzsteinhorn',
    name: 'Kitzsteinhorn — Top of Salzburg',
    emoji: '🏔️',
    what: 'Gondolas to 3,029 m on a real glacier — snow underfoot in July, viewing platform into the Hohe Tauern.',
    more: 'Three lift stages from Kaprun do ALL the work; at the top: the Top of Salzburg platform, a cinema lounge, ice grotto, and July snow you can actually touch. 0–5°C up top — bring real layers. Half a day door-to-door. The single biggest “are we really standing here” view of the Zell leg.',
    drive: '🚗 15 min · 12 km from Zell am See',
    duration: 'half day',
    difficulty: 'flat',
    chips: ['~€52', 'all lift, no climbing', 'bring layers'],
    photo: P('Kitzsteinhorn3.jpg'),
    star: true,
    maps: G('Kitzsteinhorn Gletscherbahnen Kaprun'),
  },
  {
    id: 'schmittenhoehe',
    name: 'Schmittenhöhe cable car',
    emoji: '🚡',
    what: "Zell's own mountain — cable car to 1,965 m for the full lake-from-above panorama.",
    more: 'The classic Zeller See postcard: turquoise lake, town, and thirty 3,000 m peaks on the horizon. Easy summit strolls on wide gravel paths (as short or long as you like), a panorama terrace, and back down for a swim. The lowest-effort/highest-reward half day in Zell.',
    drive: '🚗 8 min · 4 km from Zell am See',
    duration: 'half day',
    difficulty: 'easy',
    chips: ['~€36', 'easiest big view'],
    photo: P('2017-07-21%20%28197%29%20Schmittenh%C3%B6he%20in%20Zell%20am%20See%2C%20Austria.jpg'),
    maps: G('Schmittenhöhebahn Zell am See'),
  },
  {
    id: 'mooserboden',
    name: 'Mooserboden high dams',
    emoji: '🌊',
    what: 'Buses + a funicular lift you to two turquoise reservoirs at 2,040 m ringed by glaciers.',
    more: 'The Kaprun high-mountain reservoirs: you ride shuttle buses and Europe’s largest open inclined lift, then walk FLAT along the dam crowns between glacier walls. Optional dam-wall guided tour inside the dam. Vehicle-assisted altitude at its purest — huge drama, zero climb.',
    drive: '🚗 20 min · 15 km from Zell am See to Kesselfall, then included bus+lift',
    duration: 'half day',
    difficulty: 'flat',
    chips: ['~€29 incl. buses', 'flat dam walks'],
    photo: P('Kaprun%20-%20Stausee%20Mooserboden%20mit%20Denkmal.JPG'),
    maps: G('Kesselfall Alpenhaus Kaprun'),
  },
  {
    id: 'zell-cruise',
    name: 'Zeller See sunset cruise',
    emoji: '⛵',
    what: 'An evening boat across your own lake while the sun drops behind the peaks.',
    more: 'MS Schmittenhöhe runs evening rounds on the Zeller See in summer — Monday evening is your window. Board at the Esplanade, glide an hour on gold water. Your Montenegro boat-evening, Austrian edition. If the schedule shifts, the standard last round-trip of the day still catches the light.',
    drive: '🚗 0 — walk to the Esplanade pier from der Sonnberg (~15 min downhill)',
    duration: '~1h on the water',
    difficulty: 'flat',
    chips: ['~€18', 'Monday = your night'],
    photo: P('20190624.Zell%20am%20See.-014.jpg'),
    sunset: true,
    star: true,
    maps: G('Schifffahrt Zell am See Esplanade'),
  },
  {
    id: 'strandbad-zell',
    name: 'Strandbad Zell swim',
    emoji: '🏊',
    what: 'The town lido — swim off the decks straight into open alpine lake water.',
    more: 'Lawns, decks, diving platforms, warm-enough July water (~21°C), mountains all around. The default “slow shoulder” of every Zell day — an hour here resets everything. Quieter alternative across the lake: Strandbad Thumersbach, with the better view back at town.',
    drive: '🚗 5 min · 2 km from der Sonnberg (Thumersbach: 10 min · 6 km)',
    duration: '1–3h',
    difficulty: 'flat',
    chips: ['~€7'],
    photo: P(
      '2017-07-21%20%28177%29%20Beach%20promenade%20at%20Zeller%20See%2C%20Zell%20am%20See%2C%20Austria.jpg',
    ),
    swim: true,
    maps: G('Strandbad Zell am See'),
  },
  {
    id: 'sigmund-thun',
    name: 'Sigmund-Thun-Klamm gorge',
    emoji: '💦',
    what: 'A wooden boardwalk hung above rushing glacier water in a narrow rock gorge.',
    more: '320 m of walkway over the roaring Kapruner Ache, ending at the calm Klammsee with a flat lakeside loop. Short, dramatic, cool on a hot afternoon. ~1h all in — a perfect filler between a mountain morning and a lake evening.',
    drive: '🚗 12 min · 9 km from Zell am See',
    duration: '~1h',
    difficulty: 'easy',
    chips: ['~€3.50', 'boardwalk + lake loop'],
    photo: P('Kaprun%20Sigmund-Thun-Klamm%2009.JPG'),
    maps: G('Sigmund-Thun-Klamm Kaprun'),
  },
  {
    id: 'baumzipfelweg',
    name: 'Baumzipfelweg treetop walk',
    emoji: '🌲',
    what: 'A wooden path through the treetops ending at the “Golden Gate of the Alps” suspension bridge.',
    more: 'Europe’s highest treetop trail (up to 30 m over the forest floor) in Saalbach-Hinterglemm — 1 km of gentle ramps, zero steps, huge valley views from the 200 m suspension bridge. Pairs with a lazy valley afternoon.',
    drive: '🚗 40 min · 30 km from Zell am See',
    duration: '~1.5h',
    difficulty: 'easy',
    chips: ['~€15', 'ramps, no steps'],
    photo: P('S-H-Glemmtal-H%C3%A4ngebr%C3%BCcke-4.jpg'),
    maps: G('Baumzipfelweg Saalbach-Hinterglemm'),
  },
  {
    id: 'grossglockner',
    name: 'Grossglockner High Alpine Road',
    emoji: '🛣️',
    what: "Austria's most famous drive — 48 km of hairpins to ~2,400 m, ending face-to-face with the Pasterze glacier.",
    more: 'The car does 100% of the climbing: 36 hairpins, waterfalls, marmots at the top, and the Kaiser-Franz-Josefs-Höhe terrace staring straight at Austria’s highest peak (3,798 m) and its glacier. Stop wherever you gasp. Needs CLEAR weather — check the webcam that morning; toll ~€45/car. Road open ~06:00–21:30 in summer.',
    drive:
      '🚗 Sunday: 1h45 · ~115 km from Bad Goisern to the road entrance (Fusch) · from Zell: 25 min · 15 km · ~45 min more up to the glacier terrace',
    duration: 'half–full day',
    difficulty: 'flat',
    chips: ['toll ~€45/car', 'zero walking required', 'clear-weather day only'],
    photo: P('Kitzsteinhorn3.jpg'),
    star: true,
    maps: G('Grossglockner Hochalpenstrasse Fusch'),
  },

  // ---- Gosau / Salzkammergut leg -------------------------------------------
  {
    id: 'gosausee',
    name: 'Vorderer Gosausee mirror loop',
    emoji: '🪞',
    what: 'A mirror-still alpine lake with the Dachstein glacier reflected in it — flat 1-hour gravel circle.',
    more: 'THE “we’re really here” moment. 4.3 km around, zero elevation, benches everywhere; the Dachstein doubles in the water on calm evenings. After ~17:00 the tour buses leave and it’s nearly empty — go at golden hour, and again any time you want (it’s 14 minutes from the apartment). Cold clear water — brave dip optional.',
    drive: '🚗 14 min · 9 km from Gosau (30 min · 22 km from Bad Goisern)',
    duration: '~1–1.5h loop',
    difficulty: 'flat',
    chips: ['free', 'empty after 17:00'],
    photo: P('Vorderer%20Gosausee%204.jpg'),
    sunset: true,
    star: true,
    swim: true,
    maps: G('Vorderer Gosausee'),
  },
  {
    id: 'krippenstein',
    name: 'Krippenstein — 5 Fingers',
    emoji: '🖐️',
    what: 'Gondola to 2,109 m; the 5 Fingers platform hangs over a 400 m drop above Hallstatt’s lake.',
    more: 'Two gondola stages from Obertraun, then an easy 20-minute stroll to the hand-shaped viewing platform — five walkways over the void, each with a different gimmick (glass floor, photo frame). Karst plateau moonscape all around. We are deliberately SKIPPING the Dachstein ice cave (1,400 stairs, 0°C). Weather matters — clouds kill the view.',
    drive: '🚗 30 min · 24 km from Gosau · 25 min · 20 km from Bad Goisern',
    duration: 'half day',
    difficulty: 'easy',
    chips: ['~€40', 'lift + easy stroll', 'clear-day pick'],
    photo: P('A-Krippenstein-5fingers.jpg'),
    star: true,
    maps: G('Dachstein Krippenstein Seilbahn Obertraun'),
  },
  {
    id: 'hallstatt',
    name: 'Hallstatt, the quiet way',
    emoji: '🏘️',
    what: 'The famous 7,000-year-old salt village on the lake — market square, lakeshore promenade, small electric boat.',
    more: 'Go EARLY (before 09:30) or after 17:00 — midday is tour-bus chaos. The move: park P1, wander the market square and the swan harbor, then rent a small electric boat (~€25/h) and see the village from the water — the view everyone photographs, without the crowd around you. NOTE: the Skywalk viewing platform is CLOSED for 2026 (verified) — the boat is the better angle anyway.',
    drive: '🚗 25 min · 19 km from Gosau · 20 min · 17 km from Bad Goisern',
    duration: '2–3h',
    difficulty: 'flat',
    chips: ['boat ~€25/h', 'go early or late', 'Skywalk closed 2026'],
    photo: P('Marktplatz%2C%20Hallstatt%2C%2017.05.2019.jpg'),
    swim: false,
    maps: G('Hallstatt Marktplatz'),
  },
  {
    id: 'gosaukammbahn',
    name: 'Gosaukammbahn + Zwieselalm',
    emoji: '🚡',
    what: 'The little cable car at the Gosausee up to a green alpine plateau facing the Dachstein wall.',
    more: 'From the lake station straight up to gentle meadow paths, huts with drinks on sun terraces, and the full Gosaukamm rock wall in your face. Combine with the lake loop below for the complete Gosau day without a single climbed meter.',
    drive: '🚗 14 min · 9 km from Gosau (same lot as the Gosausee)',
    duration: '2–3h',
    difficulty: 'easy',
    chips: ['~€27', 'meadow strolls'],
    photo: P('Gosau%20with%20Gosaukamm.jpg'),
    maps: G('Gosaukammbahn'),
  },
  {
    id: 'langbathsee',
    name: 'Langbathsee swim loop',
    emoji: '🌿',
    what: 'A flat, quiet forest lake with a 1-hour shore loop — swimmable, almost empty.',
    more: 'The Vorderer Langbathsee sits in a nature reserve under the Höllengebirge: paved-flat 1h loop, grassy swim spots, water to ~24°C in late July, and a fraction of the crowds anywhere famous. The “nothing to achieve today” option — bring the picnic.',
    drive: '🚗 45 min · 40 km from Gosau · 35 min · 32 km from Bad Goisern',
    duration: '2–4h with swim',
    difficulty: 'flat',
    chips: ['free', 'quiet'],
    photo: P('Vorderer%20Langbathsee.jpg'),
    swim: true,
    maps: G('Vorderer Langbathsee'),
  },
  {
    id: 'almsee',
    name: 'Almsee — the quietest mirror',
    emoji: '🪞',
    what: 'A shallow crystal mirror lake at the head of the Almtal — flat 1h45 loop, herons and silence.',
    more: 'The furthest quiet-lake option and the most silent: reeds, gliding birds, the Totes Gebirge wall behind. No lifts, no tickets, no crowds — just the loop and the stillness. Only worth it as a deliberate slow half-day.',
    drive: '🚗 1h20 · 75 km from Gosau',
    duration: 'half day',
    difficulty: 'easy',
    chips: ['free', 'QUIETEST pick'],
    photo: P('Almsee%20Nordbucht-4224.jpg'),
    maps: G('Almsee Grünau im Almtal'),
  },
  {
    id: 'schafberg',
    name: 'Schafberg steam train + Wolfgangsee',
    emoji: '🚂',
    what: 'A 130-year-old steam cog railway pushes you up to 1,783 m — the classic three-lakes panorama.',
    more: 'From St. Wolfgang the SchafbergBahn climbs to the famous summit view over Wolfgangsee, Mondsee and Attersee (~35 min each way). Below: the Wolfgangsee ferry, lakeside swimming, and St. Wolfgang’s painted lanes. BOOK online at ticketing.5schaetze.at — €61 round trip, or the Kombikarte train+boat from €61 (verified Jul 20). Uphill is flexible (every ~20 min); you choose your DOWNHILL slot at purchase — take ~13:00 down to make Zell check-in. The romance option.',
    drive: '🚗 35 min · 28 km from Bad Goisern (via Bad Ischl) · 50 min from Gosau',
    duration: 'half–full day',
    difficulty: 'flat',
    chips: [
      '€61 return — RESERVE online (Kombikarte train+boat from €61)',
      'downhill slot chosen at booking',
    ],
    photo: P('Wolfgangsee%20mit%20St.%20Wolfgang.jpg'),
    star: true,
    swim: true,
    maps: G('SchafbergBahn St. Wolfgang'),
  },
  {
    id: 'katrin',
    name: 'Katrin cable car',
    emoji: '🚡',
    what: 'Bad Ischl’s own little mountain — nostalgic cable car to easy ridge paths over the whole Salzkammergut.',
    more: 'Small, uncrowded, local: up in 15 minutes, gentle summit paths with lake-dotted views in every direction, hut with terrace. A half-day at most — pairs with the Jewish Ischl walk and groceries below.',
    drive: '🚗 20 min · 16 km from Bad Goisern · 30 min · 25 km from Gosau',
    duration: '2–3h',
    difficulty: 'easy',
    chips: ['~€28', 'local + quiet'],
    photo: P('Ischl%20from%20the%20Katrin.JPG'),
    maps: G('Katrin Seilbahn Bad Ischl'),
  },

  // ---- Bavaria / cross-border ----------------------------------------------
  {
    id: 'koenigssee',
    name: 'Königssee silent-boat day',
    emoji: '🚤',
    what: "Bavaria's fjord — silent electric boats under sheer cliffs, the echo trumpet, St. Bartholomä, and the Obersee mirror lake.",
    more: 'Since 1909 only silent electric boats run this 8 km lake walled by the Watzmann. Mid-lake the captain stops and plays a trumpet at the Echo Wall — the mountain answers. Off at St. Bartholomä (the red onion-dome chapel), on to Salet, then a FLAT 15-min walk to the Obersee: perfectly still water with Germany’s highest waterfall (470 m) on the far cliff. €29.80 Salet return; be at the dock before 10:30 (queues + calmest water). CALL AHEAD for the last Salet return boat (+49 8652 9636-0). Bring a picnic — nothing kosher on site. Glacial water: a dip, not a swim.',
    drive: '🚗 1h06 · 75 km from Gosau (on the way to Wals) · 30 min · 25 km from Wals',
    duration: 'full day',
    difficulty: 'flat',
    chips: ['€29.80', 'boat does everything', 'be there by 10:30'],
    photo: P('K%C3%B6nigssee%20St.%20Bartholom%C3%A4%2002.jpg'),
    star: true,
    maps: G('Königssee Seelände Schönau'),
  },
  {
    id: 'rossfeld',
    name: 'Rossfeld panorama sunset road',
    emoji: '🌅',
    what: 'A ridge-top toll road you simply drive — sunset over two countries with zero walking.',
    more: 'The Rossfeld Panoramastraße loops along the ridge above Berchtesgaden at ~1,560 m: park at the top pullouts, step out, watch the sun go down over Salzburg on one side and the Berchtesgaden Alps on the other. €9.50/car, always open. The perfect zero-effort sunset after the Königssee day.',
    drive: '🚗 24 min · 18 km from the Königssee · 30 min · 26 km from Wals',
    duration: '~1h at golden hour',
    difficulty: 'flat',
    chips: ['€9.50/car', 'zero walking'],
    photo: P('Kehlsteinhaus%202.jpg'),
    sunset: true,
    maps: G('Rossfeld Panoramastrasse'),
  },
  {
    id: 'hintersee-ramsau',
    name: 'Hintersee + Zauberwald (Bavaria)',
    emoji: '🪞',
    what: 'A tiny, achingly-still mirror lake with rowboats, plus the mossy “enchanted forest” boulder path.',
    more: 'Ramsau’s Hintersee mirrors the Hochkalter on calm mornings; rent a rowboat (~€10/30min) or walk the flat 1h shore loop, then drift the Zauberwald path along the glacier stream — moss, boulders, cold clear water. Add the 5-min stop at Ramsau’s St. Sebastian church bridge — Germany’s most-photographed church view. All flat, all quiet.',
    drive: '🚗 1h17 · 78 km from Gosau · 36 min · 30 km from Wals',
    duration: 'half day',
    difficulty: 'flat',
    chips: ['free', 'rowboat ~€10', 'all flat'],
    photo: P('Hintersee-Hochkalter.jpg'),
    swim: true,
    sunset: true,
    maps: G('Hintersee Ramsau bei Berchtesgaden'),
  },
  {
    id: 'chiemsee',
    name: 'Chiemsee island-boat day',
    emoji: '⛴️',
    what: '“The Bavarian Sea” — lake steamer to Ludwig II’s unfinished Versailles and a tiny car-free nuns’ island.',
    more: 'From Prien, steamers hop to Herreninsel — King Ludwig II’s Herrenchiemsee palace, a deliberate Versailles copy with a jaw-drop hall of mirrors (guided tour ~€11) — then to Fraueninsel, a car-free island village with a 1,200-year-old abbey, smoked-fish stands and lake swimming. The gentlest big-water day available; the cultural alternative to the Königssee.',
    drive: '🚗 42 min · 55 km from Wals',
    duration: 'full day',
    difficulty: 'flat',
    chips: ['boat ~€12 + palace €11', 'gentlest big day'],
    photo: P('Herrenchiemsee%20Neues%20Schloss%20Ost%20Auffahrtsallee.jpg'),
    swim: true,
    maps: G('Chiemsee Schifffahrt Prien'),
  },
  {
    id: 'eagles-nest',
    name: 'Eagle’s Nest (Kehlsteinhaus)',
    emoji: '🏛️',
    what: 'Hitler’s mountaintop house — today a viewpoint reached by special bus + elevator; heavy history, huge views.',
    more: 'Special buses climb the private road, then a brass elevator inside the mountain. The building is now a restaurant/viewpoint with a documentation panel; the view over the Berchtesgaden Alps is immense. Some visitors find going meaningful (seeing it demystified), others prefer not to give it the time — entirely your call, zero judgment. ~€36 bus+elevator.',
    drive: '🚗 35 min · 28 km from Wals to the Obersalzberg bus terminal',
    duration: '~3h',
    difficulty: 'easy',
    chips: ['~€36', 'bus + elevator', 'your call'],
    photo: P('Kehlsteinhaus%202.jpg'),
    maps: G('Kehlsteinhaus Dokumentation Obersalzberg'),
  },

  // ---- Gems (added Jul 20 "what would we love" hunt) -----------------------
  {
    id: 'gosausee-boats',
    name: 'E-boat or SUP ON the Gosausee',
    emoji: '🛶',
    what: 'Rent a silent electric boat or paddleboard on your own mirror lake — float inside the Dachstein reflection.',
    more: 'License-free e-boats (€26/h), SUP (€17/h) and pedal boats right at the Vorderer Gosausee. You are already going for the shore loop — this puts you ON the mirror. Daily 10:00–18:00 on fair-weather days (Jun–Sep). Calmest water = morning. Cash-friendly, walk-up.',
    drive: '🚗 14 min · 9 km from Gosau (same lot as the lake loop)',
    duration: '~1h',
    difficulty: 'flat',
    chips: ['e-boat €26/h · SUP €17/h', '10:00–18:00, sunny days', 'walk-up'],
    photo: P('Vorderer%20Gosausee%204.jpg'),
    swim: true,
    star: true,
    maps: G('Vorderer Gosausee'),
  },
  {
    id: 'grundlsee-3lakes',
    name: 'Grundlsee 3-Lakes tour → hidden Kammersee',
    emoji: '🚣',
    what: 'Big boat across the Grundlsee, a gentle forest walk, then a WOODEN boat up the fjord-like Toplitzsee to a hidden third lake.',
    more: 'The Salzkammergut’s secret: cruise the Grundlsee, stroll ~25 easy minutes through forest, then board a traditional wooden Plätte up the Toplitzsee — cliffs and waterfalls on both sides — to tiny Kammersee, where the Traun river is born from the rock. Sit-down the whole way, mystical, uncrowded. ~€35, ~3–4h all in. Check the day’s departure times at schifffahrt-grundlsee.at before driving.',
    drive: '🚗 25 min · 22 km from Bad Goisern · 50 min · 42 km from Gosau',
    duration: '3–4h',
    difficulty: 'easy',
    chips: ['~€35', 'wooden-boat magic', 'check times before going'],
    photo: P('Grundlsee%20from%20G%C3%B6%C3%9Fl%20' + '20210926.jpg'),
    star: true,
    maps: G('Schifffahrt Grundlsee'),
  },
  {
    id: 'tauern-spa',
    name: 'Tauern Spa Kaprun — evening pools',
    emoji: '♨️',
    what: 'Warm panoramic pools facing the Kitzsteinhorn — the cozy-evening upgrade, 11 minutes from your Zell bed.',
    more: 'Indoor-outdoor water world with mountain views; evening ticket from ~€25.50 (entry from 17:00, pools to 21:00 — book at shop.tauernspakaprun.com, prices float). It is just water — kosher-trivial. Note: the pool world is swimsuit; simply skip the (separate, nude) sauna wing. Perfect after a glacier or Grossglockner day, and you can still catch the Esplanade sunset after.',
    drive: '🚗 11 min · 8 km from Zell am See',
    duration: '2–3h evening',
    difficulty: 'flat',
    chips: ['evening from ~€25.50', 'pools to 21:00', 'swimsuit pools'],
    photo: P(
      '2017-07-21%20%28177%29%20Beach%20promenade%20at%20Zeller%20See%2C%20Zell%20am%20See%2C%20Austria.jpg',
    ),
    swim: true,
    maps: G('Tauern Spa Kaprun'),
  },
  {
    id: 'wolfgangsee-eboat',
    name: 'Your own e-boat on the Wolfgangsee',
    emoji: '🛥️',
    what: 'Rent a little red electric boat (5 seats, sun canopy) and swim off it in the middle of the lake.',
    more: 'Wassersport Engel, St. Gilgen waterfront: license-free e-boats €35/h (July “deluxe” with lounging deck + swim ladder €40/h). No reservations — arrive at opening (10:00) on the Schafberg day and take the first hour as your slow shoulder. Daily to 18:00, fair weather.',
    drive:
      '🚗 at the Wolfgangsee — 29 min · 25 km from Bad Goisern (same day as the Schafberg train)',
    duration: '~1h',
    difficulty: 'flat',
    chips: ['€35–40/h', 'no reservation — go at 10:00', 'swim ladder'],
    photo: P('Wolfgangsee%20mit%20St.%20Wolfgang.jpg'),
    swim: true,
    maps: G('Wassersport Engel St. Gilgen'),
  },
  {
    id: 'hallstatt-sup',
    name: 'SUP the quiet end of the Hallstättersee',
    emoji: '🏄',
    what: 'Paddleboard from the calm north shore — glassy morning water, Hallstatt’s crowds 8 km away across the lake.',
    more: 'Board rental at the Gosaumühle north end (≈€25 half-day incl. vest + dry-bag, daily 9:00–18:00). Morning is glassiest — mountains double in the water. This was the May “trip-postcard” dream: SUP on the Hallstättersee, without going anywhere near the village crush. Call ahead to confirm a morning slot.',
    drive: '🚗 9 min · 7 km from Bad Goisern · 20 min · 16 km from Gosau',
    duration: '2–4h',
    difficulty: 'easy',
    chips: ['~€25 half-day', 'mornings = glass', 'call ahead'],
    photo: P('Marktplatz%2C%20Hallstatt%2C%2017.05.2019.jpg'),
    swim: true,
    maps: G('Roadhouse Gosaumühle Hallstättersee'),
  },

  // ---- Salzburg-side easies -------------------------------------------------
  {
    id: 'untersberg',
    name: 'Untersberg cable car',
    emoji: '🚡',
    what: 'The big cliff face over Salzburg — cable car to 1,776 m in 8.5 minutes, alpine world instantly.',
    more: 'Right next to the Wals hotel: a swinging ride up the rock face to summit paths, ridge viewpoints over the whole Salzburg basin, and mountain air before your flight home. Short easy walks from the top station; go as far as feels nice.',
    drive: '🚗 10 min · 7 km from Wals',
    duration: '2–3h',
    difficulty: 'easy',
    chips: ['~€32', '8.5 min to the top'],
    photo: P('Untersbergbahn%202019.jpg'),
    maps: G('Untersbergbahn Grödig'),
  },
  {
    id: 'hellbrunn',
    name: 'Hellbrunn trick fountains',
    emoji: '⛲',
    what: 'A 400-year-old pleasure palace whose gardens are booby-trapped with hidden water jets — genuinely funny.',
    more: 'The prince-archbishop built a garden to soak his guests and it still works: stone seats that spray, grottos, a water-driven puppet theater. Flat shaded gardens for free wandering, fountain tour ~€13.50. The laugh-out-loud option — good flight-day morning or arrival-day softener.',
    drive: '🚗 15 min · 10 km from Wals or from Salzburg center',
    duration: '~2h',
    difficulty: 'flat',
    chips: ['~€13.50', 'shaded + funny'],
    photo: P('Hellbrunn%20Palace-Schloss%20Hellbrunn.%20Salzburg%2C%20Austria.jpg'),
    maps: G('Schloss Hellbrunn'),
  },
  {
    id: 'moenchsberg',
    name: 'Mönchsberg clifftop walk',
    emoji: '🌇',
    what: 'Salzburg’s old-town cliff — stone stairs up, ridge path along the top, fortress and river views.',
    more: 'Free stone stairs from the Altstadt (or the €3 lift), then a wooded ridge walk above the rooftops: the fortress on one end, the Museum der Moderne terrace on the other, and the classic overlook of domes + river + mountains. Best in the evening — the city goes gold below you.',
    drive: '🚗 15 min · 8 km from Wals to Altstadt parking, then on foot',
    duration: '~1.5–2h',
    difficulty: 'easy',
    chips: ['free (lift €3)', 'evening gold'],
    photo: P('Salzburg%20Altstadt%20Panorama%20' + '20170409%2002.jpg'),
    sunset: true,
    maps: G('Mönchsberg Salzburg'),
  },
  {
    id: 'mirabell',
    name: 'Mirabell Gardens',
    emoji: '🌹',
    what: 'The baroque palace gardens with the postcard fortress view (yes, the Sound of Music steps).',
    more: 'Free, central, flat: parterre flowers, the dwarf garden, the pergola, and the exact framed view of Hohensalzburg fortress everyone knows. 45 gentle minutes, pairs with anything in town.',
    drive: '🚗 15 min · 8 km from Wals · in-town on foot',
    duration: '~45 min',
    difficulty: 'flat',
    chips: ['free'],
    photo: P('Salzburg%20Mirabellgarten%20Festung.jpg'),
    maps: G('Mirabellgarten Salzburg'),
  },
  {
    id: 'golling',
    name: 'Gollinger Wasserfall',
    emoji: '💦',
    what: 'A fairy-tale double-drop waterfall in the forest — short walk, maximum wow-per-step.',
    more: 'From the lot, ~15 minutes of easy forest path to the lower platform (the money view); wooden stairs continue higher if legs agree. ~1h round trip, €5. A classic pull-over between Salzburg and the south.',
    drive: '🚗 25 min · 28 km from Wals',
    duration: '~1h',
    difficulty: 'easy',
    chips: ['€5', 'short + dramatic'],
    photo: P('Beautiful%20Gollinger%20Wasserfall.jpg'),
    maps: G('Gollinger Wasserfall'),
  },

  // ---- ADDED 2026-07-23 from the verified research sweep ------------------
  // 4 lanes → 63 candidates → every one adversarially fact-checked, 63/63
  // survived. Fills the four real holes in the original 36: no rafting, no
  // train but the Schafberg, NO GORGE at all, and nothing walkable for Shabbat.
  {
    id: 'frost-rafting',
    name: 'FROST family rafting — the Salzach',
    emoji: '🚣',
    what: 'A gentle guided raft float — 5 km, only ~45 min actually on the water, grade 2+ maximum.',
    more: 'The scenic float, not a workout: small waves, a guide doing the steering, age 6 and up, about 2 hours door to door from the Frost Camp on the Salzach. €55 pp on FROST’s current published price list (the list carries no year stamp — reconfirm when you book). MUST BE BOOKED DIRECT: it runs ON REQUEST only, is sold on no platform at all (CheckYeti lists only their white-water tour), and needs 24 hours’ notice. There is no published minimum group size, so ask outright whether it will run for two people. Email info@frostrafting.at. Sat-nav to Hauserdorfstraße 2, 5662 — NOT “Taxenbach”, which is how the booking sites file them.',
    drive: '🚗 11 min · 9.5 km from Zell am See',
    duration: '~2h total, 45 min on the river',
    difficulty: 'easy',
    chips: ['€55 pp', 'BOOK AHEAD — on request only', 'age 6+', 'season to 15 Sept'],
    photo:
      'data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20400%20200%22%3E%3Crect%20width%3D%22400%22%20height%3D%22200%22%20fill%3D%22%23dfeaf2%22%2F%3E%3Ctext%20x%3D%22200%22%20y%3D%22128%22%20font-size%3D%2286%22%20text-anchor%3D%22middle%22%3E%F0%9F%9A%A3%3C%2Ftext%3E%3C%2Fsvg%3E',
    swim: true,
    star: true,
    maps: G('Frost Rafting Hauserdorfstraße 2 Bruck an der Großglocknerstraße'),
  },
  {
    id: 'taxenbach-rafting',
    name: 'Rafting Center Taxenbach',
    emoji: '🛶',
    what: 'The bigger Salzach run — grade 3/4, about 2 hours on the river out of 4 door to door.',
    more: 'Four departures a day: 09:00, 10:00, 13:00 and 14:00. €64 adult (€54 for 12–15). BOOK DIRECT on +43 664 4025149 — the Adventure Service resale is €68.50, i.e. MORE expensive, not less. Ignore the €48 you will see advertised on their own homepage; that is a stale teaser. 19 minutes from the Zell bed.',
    drive: '🚗 19 min · 18 km from Zell am See',
    duration: '~4h total, ~2h on the river',
    difficulty: 'moderate',
    chips: ['€64 adult', 'book direct — resale costs more', '09:00 · 10:00 · 13:00 · 14:00'],
    photo:
      'data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20400%20200%22%3E%3Crect%20width%3D%22400%22%20height%3D%22200%22%20fill%3D%22%23dfeaf2%22%2F%3E%3Ctext%20x%3D%22200%22%20y%3D%22128%22%20font-size%3D%2286%22%20text-anchor%3D%22middle%22%3E%F0%9F%9A%A3%3C%2Ftext%3E%3C%2Fsvg%3E',
    swim: true,
    maps: G('Rafting Center Taxenbach'),
  },
  {
    id: 'out2-rafting',
    name: 'OUT2 rafting — from Zell town centre',
    emoji: '🚣',
    what: '11 km of grade 3–4 water, starting from an office you can walk to from the Zell apartment.',
    more: 'Franz-Josef-Straße 7, in the middle of Zell — no drive at all. €65 adult, €60 under 15 (CheckYeti from €60). Age 10 with an adult. Two slots: 09:00–13:00 and 14:00–18:00 — the German page says 18:30, so do not schedule anything tight afterwards. Budget about 5 hours door to door. Book ahead.',
    drive: '🚗 0 — in Zell am See itself',
    duration: '~5h door to door',
    difficulty: 'moderate',
    chips: ['€65 adult', 'walkable from the Zell bed', 'book ahead', 'age 10+'],
    photo:
      'data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20400%20200%22%3E%3Crect%20width%3D%22400%22%20height%3D%22200%22%20fill%3D%22%23dfeaf2%22%2F%3E%3Ctext%20x%3D%22200%22%20y%3D%22128%22%20font-size%3D%2286%22%20text-anchor%3D%22middle%22%3E%F0%9F%9A%A3%3C%2Ftext%3E%3C%2Fsvg%3E',
    swim: true,
    maps: G('OUT2 Zell am See Franz-Josef-Straße 7'),
  },
  {
    id: 'lofer-basecamp',
    name: 'Base Camp Lofer — Panorama raft',
    emoji: '🚣',
    what: 'Their easiest raft: 11 km of grade II water that crosses into Bavaria mid-river.',
    more: '€74 adult, age 6 and up, about 3 hours. Daily 09:00–19:00, season to end September. Their price list is still headed “Preisliste 2025”, so expect a small rise. Book DIRECT — CheckYeti adds €7–14 pp. NOTE for Monday 27 July: the other Lofer operator (Motion) is CLOSED MONDAYS across rafting, canoe and canyoning; Base Camp and FROST are open.',
    drive: '🚗 36 min · 40 km from Zell am See',
    duration: '~3h',
    difficulty: 'easy',
    chips: ['€74 adult', 'age 6+', 'book direct — cheapest channel'],
    photo:
      'data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20400%20200%22%3E%3Crect%20width%3D%22400%22%20height%3D%22200%22%20fill%3D%22%23dfeaf2%22%2F%3E%3Ctext%20x%3D%22200%22%20y%3D%22128%22%20font-size%3D%2286%22%20text-anchor%3D%22middle%22%3E%F0%9F%9A%A3%3C%2Ftext%3E%3C%2Fsvg%3E',
    swim: true,
    maps: G('Base Camp Lofer Hallenstein 25'),
  },
  {
    id: 'pathfinder-kayak',
    name: 'Kayak, canoe or SUP on the Hallstättersee',
    emoji: '🛶',
    what: 'Your own boat delivered to the Gosaumühle car park, on the quiet end of the Hallstatt lake.',
    more: 'Single kayak €40 day / €30 half · double €60/€45 · canoe €60/€45 · SUP €35/€25. Half-days are 09:00–13:00 or 13:00–17:00 and the CHECK-IN WINDOWS ARE FIXED (09:00–10:00 or 13:00–14:00). Life jackets come with kayaks and canoes but NOT with the SUP. MUST be booked at least a day ahead, best by phone on +43 664 25 27 059 — and the office is only open Mon–Fri 09:00–12:00, so a Saturday or Sunday boat means calling Friday morning at the latest.',
    drive: '🚗 9 min · 7 km from Bad Goisern',
    duration: 'half day',
    difficulty: 'easy',
    chips: [
      'SUP €25 half-day · kayak €30',
      'BOOK ≥1 day ahead — office Mon–Fri 09–12',
      'fixed check-in window',
    ],
    photo:
      'data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20400%20200%22%3E%3Crect%20width%3D%22400%22%20height%3D%22200%22%20fill%3D%22%23dfeaf2%22%2F%3E%3Ctext%20x%3D%22200%22%20y%3D%22128%22%20font-size%3D%2286%22%20text-anchor%3D%22middle%22%3E%F0%9F%9A%A3%3C%2Ftext%3E%3C%2Fsvg%3E',
    swim: true,
    maps: G('Gosaumühle Hallstättersee'),
  },
  {
    id: 'hallstattersee-boat',
    name: 'Lake boat from your own Bad Goisern shore',
    emoji: '⛴',
    what: 'The scheduled Hallstättersee boat calls at Untersee and Steeg — Bad Goisern’s own lakefront.',
    more: 'THE FIND: the northern route only runs 18 July – 16 August, and your week lands inside it. Boards Untersee 10:40 and 16:40, Steeg 11:20 and 17:25. The northern fare is published nowhere — pay on board, CASH ONLY, no bikes. (For reference the southern round trip from Hallstatt Markt is €18 adult, departing 11:00/13:00/14:00/15:00/16:00 — there is no 10:00.) A boat on the lake you are sleeping beside, without driving anywhere.',
    drive: '🚗 8 min · 5 km to the Untersee pier',
    duration: '~1–2h',
    difficulty: 'flat',
    chips: ['CASH ONLY — fare unpublished', 'only runs 18 Jul – 16 Aug', 'Untersee 10:40 · 16:40'],
    photo:
      'data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20400%20200%22%3E%3Crect%20width%3D%22400%22%20height%3D%22200%22%20fill%3D%22%23dfeaf2%22%2F%3E%3Ctext%20x%3D%22200%22%20y%3D%22128%22%20font-size%3D%2286%22%20text-anchor%3D%22middle%22%3E%F0%9F%9A%A3%3C%2Ftext%3E%3C%2Fsvg%3E',
    star: true,
    maps: G('Schifffahrt Hallstättersee Untersee Bad Goisern'),
  },
  {
    id: 'strandbad-untersee',
    name: 'Strandbad Untersee',
    emoji: '🏊',
    what: 'Free lakeside lido with a jetty, floating raft, trampoline and a 3 m diving tower.',
    more: 'Entry is free; PARKING is €2.20/hour or €11 a day — the English page still says parking is free and it is not. Buffet open May to mid-September, roughly 09:00–22:00. There is a separate FKK section at the back; the main beach is ordinary. Eight minutes from the Bad Goisern bed.',
    drive: '🚗 8 min · 5 km from Bad Goisern',
    duration: '2–4h',
    difficulty: 'flat',
    chips: ['free entry · parking €11/day', 'diving tower + trampoline'],
    photo:
      'data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20400%20200%22%3E%3Crect%20width%3D%22400%22%20height%3D%22200%22%20fill%3D%22%23dfeef0%22%2F%3E%3Ctext%20x%3D%22200%22%20y%3D%22128%22%20font-size%3D%2286%22%20text-anchor%3D%22middle%22%3E%F0%9F%8F%8A%3C%2Ftext%3E%3C%2Fsvg%3E',
    swim: true,
    maps: G('Strandbad Untersee Bad Goisern'),
  },
  {
    id: 'parkbad-goisern',
    name: 'Parkbad Bad Goisern — the Shabbat answer',
    emoji: '🏊',
    what: 'The village pool, walkable from the apartment — the one thing on this whole list that needs no car.',
    more: 'CORRECTED 23 Jul: this was first listed as “the Shabbat answer” because it is a 500 m walk. That was wrong — it charges €8.70 at the gate, which means handling money, so it does not work on Shabbat unless you sort entry in advance. It is a fine Sunday morning instead. €8.70, open 09:00–19:00. And on that same Saturday the HALLSTÄTTERSEE SWIM MARATHON is happening about 3 km along the shore at Strandbad Untersee — also walkable: swims start 09:30 (5 km), 10:00 (2.1 km) and 10:30 (the 7 km crossing from Obertraun); the first 7 km finishers arrive around 12:30, the course closes 15:30, prizes at 16:00. Spectator price is not published — the lido may charge its usual entry.',
    drive: '🚗 0 — a 500 m walk from the apartment',
    duration: '2–4h',
    difficulty: 'flat',
    chips: ['€8.70 — so not on Shabbat', 'a 500 m walk', '09:00–19:00'],
    photo:
      'data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20400%20200%22%3E%3Crect%20width%3D%22400%22%20height%3D%22200%22%20fill%3D%22%23dfeef0%22%2F%3E%3Ctext%20x%3D%22200%22%20y%3D%22128%22%20font-size%3D%2286%22%20text-anchor%3D%22middle%22%3E%F0%9F%8F%8A%3C%2Ftext%3E%3C%2Fsvg%3E',
    swim: true,
    star: true,
    maps: G('Parkbad Bad Goisern Auskei-Weg 1'),
  },
  {
    id: 'liechtensteinklamm',
    name: 'Liechtensteinklamm',
    emoji: '🏞',
    what: 'The famous deep gorge — a walkway pinned to sheer rock above roaring water.',
    more: 'The best-placed of the three gorges for your week: it sits on the Zell → Gosau drive on Tuesday 28th, so it costs you almost no extra driving. €16 at the gate, €15 online, open 09:00–18:00. IMPORTANT: queues run up to an hour between 10:00 and 14:30 — and that applies to online-ticket holders TOO, so go before 10:00 or after 14:30.',
    drive: '🚗 44 min from Zell — and it is ON the Tuesday drive to Gosau',
    duration: '~1.5h',
    difficulty: 'easy',
    chips: ['€16 gate · €15 online', 'go before 10:00 or after 14:30', 'on the Tuesday drive'],
    photo:
      'data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20400%20200%22%3E%3Crect%20width%3D%22400%22%20height%3D%22200%22%20fill%3D%22%23e2ece4%22%2F%3E%3Ctext%20x%3D%22200%22%20y%3D%22128%22%20font-size%3D%2286%22%20text-anchor%3D%22middle%22%3E%F0%9F%8F%9E%3C%2Ftext%3E%3C%2Fsvg%3E',
    star: true,
    maps: G('Liechtensteinklamm St. Johann im Pongau'),
  },
  {
    id: 'kitzlochklamm',
    name: 'Kitzlochklamm',
    emoji: '🏞',
    what: 'A short, dramatic gorge walk 20 minutes from Zell — boardwalks, tunnels and spray.',
    more: '€11 adult, CASH ONLY. Open 08:00–18:00 but LAST ENTRY IS 17:00. About an hour and a half. The nearest gorge to the Zell bed and the easiest one to slot into a half-day. Better in rain, not worse.',
    drive: '🚗 22 min · 19 km from Zell am See',
    duration: '~1.5h',
    difficulty: 'easy',
    chips: ['€11 — CASH ONLY', 'last entry 17:00', 'better in rain'],
    photo:
      'data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20400%20200%22%3E%3Crect%20width%3D%22400%22%20height%3D%22200%22%20fill%3D%22%23e2ece4%22%2F%3E%3Ctext%20x%3D%22200%22%20y%3D%22128%22%20font-size%3D%2286%22%20text-anchor%3D%22middle%22%3E%F0%9F%8F%9E%3C%2Ftext%3E%3C%2Fsvg%3E',
    maps: G('Kitzlochklamm Taxenbach'),
  },
  {
    id: 'seisenbergklamm',
    name: 'Seisenbergklamm, Weißbach',
    emoji: '🏞',
    what: 'The cheapest and shortest of the three gorges — about an hour of wooden walkway over green water.',
    more: '€9 adult, €5 child, and free with a Salzburger Saalachtal or SalzburgerLand card. HONEST CAVEAT: it is often sold as “gentle”, and it is not quite — about 300 steps and 80 m of climb. Still easy, but not flat.',
    drive: '🚗 27 min · 28 km from Zell am See',
    duration: '~1h',
    difficulty: 'easy',
    chips: ['€9 adult', '~300 steps — not flat', 'free with a Saalachtal card'],
    photo:
      'data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20400%20200%22%3E%3Crect%20width%3D%22400%22%20height%3D%22200%22%20fill%3D%22%23e2ece4%22%2F%3E%3Ctext%20x%3D%22200%22%20y%3D%22128%22%20font-size%3D%2286%22%20text-anchor%3D%22middle%22%3E%F0%9F%8F%9E%3C%2Ftext%3E%3C%2Fsvg%3E',
    maps: G('Seisenbergklamm Weißbach bei Lofer'),
  },
  {
    id: 'dachstein-icecave',
    name: 'Dachstein Giant Ice Cave + Mammut Cave',
    emoji: '🧊',
    what: 'Two enormous guided caves inside the Dachstein — real ice formations underground, in July.',
    more: 'The replacement for the closed Hallstatt salt mine. €50.20 adult covers the cable car (section 1) and BOTH guided tours; 50 minutes per cave, a 15–20 minute walk from the middle station, so about 3.5–4 hours in total. Cold underground — take a jacket. Run by Dachstein Tourismus AG.',
    drive: '🚗 37 min · 25 km from Bad Goisern (39 min from Gosau)',
    duration: '3.5–4h',
    difficulty: 'moderate',
    chips: ['€50.20 incl. cable car + both caves', 'cold — take a jacket', 'works in rain'],
    photo:
      'data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20400%20200%22%3E%3Crect%20width%3D%22400%22%20height%3D%22200%22%20fill%3D%22%23e9e4ef%22%2F%3E%3Ctext%20x%3D%22200%22%20y%3D%22128%22%20font-size%3D%2286%22%20text-anchor%3D%22middle%22%3E%F0%9F%A7%82%3C%2Ftext%3E%3C%2Fsvg%3E',
    maps: G('Dachstein Rieseneishöhle Obertraun'),
  },
  {
    id: 'salzwelten-altaussee',
    name: 'Salzwelten Altaussee salt mine',
    emoji: '🧂',
    what: 'The working salt mine — flat, warm coats, wooden slides, and the Monuments Men chambers.',
    more: 'This is the mine that is actually OPEN (Salzwelten Hallstatt is shut for renovation into summer 2026). €27, daily 09:00–16:00 until 13 September, about 90 minutes, and it is FLAT inside. The chambers where the Nazis stored looted art are part of the tour. Note: the underground salt lake belongs to the Hallein mine, not this one. 26 minutes from the Bad Goisern bed — an ideal wet-day answer.',
    drive: '🚗 26 min · 22 km from Bad Goisern',
    duration: '~1.5h',
    difficulty: 'flat',
    chips: ['€27', 'daily 09:00–16:00', 'flat inside', 'the one that is OPEN'],
    photo:
      'data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20400%20200%22%3E%3Crect%20width%3D%22400%22%20height%3D%22200%22%20fill%3D%22%23e9e4ef%22%2F%3E%3Ctext%20x%3D%22200%22%20y%3D%22128%22%20font-size%3D%2286%22%20text-anchor%3D%22middle%22%3E%F0%9F%A7%82%3C%2Ftext%3E%3C%2Fsvg%3E',
    star: true,
    maps: G('Salzwelten Altaussee'),
  },
  {
    id: 'pinzgauer-bahn',
    name: 'Pinzgauer Lokalbahn — Zell to Mittersill',
    emoji: '🚂',
    what: 'A narrow-gauge valley railway leaving from the platform in Zell — 47 minutes up the Pinzgau.',
    more: 'Hourly at :02 every day, roughly 05:02 to 22:02. The extra :32 departures are MON–FRI ONLY, not weekends. €12.80 is the full Zell–Krimml fare; Mittersill costs less. If you ride at the weekend the WEEKEND TICKET is €25 for up to three people, unlimited Saturday and Sunday. Trains now terminate at Mittersill — Krimml is a replacement bus indefinitely after 2021 flood damage, with no reopening date. Bikes must be booked by 14:00 the day before and cannot go on the bus.',
    drive: '🚗 0 — the station is in Zell am See',
    duration: '~2–3h return',
    difficulty: 'flat',
    chips: ['€12.80 full line · €25 weekend for 3', 'hourly at :02', 'Krimml section is a bus'],
    photo:
      'data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20400%20200%22%3E%3Crect%20width%3D%22400%22%20height%3D%22200%22%20fill%3D%22%23ece6da%22%2F%3E%3Ctext%20x%3D%22200%22%20y%3D%22128%22%20font-size%3D%2286%22%20text-anchor%3D%22middle%22%3E%F0%9F%9A%82%3C%2Ftext%3E%3C%2Fsvg%3E',
    maps: G('Bahnhof Zell am See Pinzgauer Lokalbahn'),
  },
  {
    id: 'taurachbahn',
    name: 'Taurachbahn steam train, Mauterndorf',
    emoji: '🚂',
    what: 'A genuine narrow-gauge steam train through the Lungau — and it runs Fri, Sat and Sun.',
    more: 'Departures 10:00 and 14:00 from Mauterndorf, returning 12:20 and 16:20. €25 return, €18 single, under-15s half price, 20% off with a Lungau Card. About 1h15 from Zell. TWO HONEST CAVEATS: it is volunteer-run, so there is no obligation to operate on any given day, and if the steam locomotive fails a diesel substitutes with no refund. HONEST PROBLEM FOR THIS TRIP: it runs Fri, Sat and Sun only — and your Friday is the arrival day, your Saturday is Shabbat with no driving, and your Sunday is the transfer to Zell. Realistically it does not fit this week unless you rebuild a day around it.',
    drive: '🚗 1h35 · 120 km from Zell am See',
    duration: '~2.5h + the drive',
    difficulty: 'flat',
    chips: ['€25 return', 'Fri · Sat · Sun only', 'volunteer-run — may not operate'],
    photo:
      'data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20400%20200%22%3E%3Crect%20width%3D%22400%22%20height%3D%22200%22%20fill%3D%22%23ece6da%22%2F%3E%3Ctext%20x%3D%22200%22%20y%3D%22128%22%20font-size%3D%2286%22%20text-anchor%3D%22middle%22%3E%F0%9F%9A%82%3C%2Ftext%3E%3C%2Fsvg%3E',
    maps: G('Taurachbahn Mauterndorf'),
  },
  {
    id: 'hallstatt-by-train',
    name: 'Hallstatt by train + ferry — no car, no parking',
    emoji: '⛴',
    what: 'The classic car-free arrival: 12 minutes by train from Bad Goisern, then the ferry across to the village.',
    more: 'Bad Goisern 10:13 → Hallstatt station 10:25, no change, calling at Steeg-Gosau. The ferry meets every train, crosses in 10–15 minutes, and costs €4 single / €8 return — CASH ONLY. You arrive at the postcard end of the village instead of fighting for a parking space. ⚠️ A special timetable (Sonderfahrplan) is in force 11 July – 3 August 2026: these are real trains, not buses, but the times are altered and ÖBB says connections are not guaranteed — re-check the day before.',
    drive: '🚗 1 min — the station is in Bad Goisern',
    duration: '~4h with the village',
    difficulty: 'flat',
    chips: ['ferry €8 return — CASH ONLY', 'special timetable 11 Jul – 3 Aug', 'no parking needed'],
    photo:
      'data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20400%20200%22%3E%3Crect%20width%3D%22400%22%20height%3D%22200%22%20fill%3D%22%23ece6da%22%2F%3E%3Ctext%20x%3D%22200%22%20y%3D%22128%22%20font-size%3D%2286%22%20text-anchor%3D%22middle%22%3E%F0%9F%9A%82%3C%2Ftext%3E%3C%2Fsvg%3E',
    star: true,
    maps: G('Bahnhof Bad Goisern'),
  },
  {
    id: 'attersee-bahn-schiff',
    name: '“Bahn & Schiff” — Attersee train + cruise',
    emoji: '🚂',
    what: 'One ticket covering the little Atterseebahn and a cruise on Austria’s largest lake.',
    more: 'Round trip South €36.30 adult, North €27.30. High season 4 July – 13 September, daily. From Vöcklamarkt: North departs 09:34 / 10:34 / 14:34 / 15:34, South 08:34 / 10:34 / 13:34–13:38. North is about 3 hours door to door, South about 4. ⚠️ Sailings get cancelled for weather and the day’s timetable is only posted from 17:00 the evening before — check then, not in the morning.',
    drive: '🚗 1h05 · 59 km from Bad Goisern',
    duration: '3–4h + the drive',
    difficulty: 'flat',
    chips: [
      '€36.30 south · €27.30 north',
      'daily 4 Jul – 13 Sept',
      'weather cancellations — check 17:00 the night before',
    ],
    photo:
      'data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20400%20200%22%3E%3Crect%20width%3D%22400%22%20height%3D%22200%22%20fill%3D%22%23ece6da%22%2F%3E%3Ctext%20x%3D%22200%22%20y%3D%22128%22%20font-size%3D%2286%22%20text-anchor%3D%22middle%22%3E%F0%9F%9A%82%3C%2Ftext%3E%3C%2Fsvg%3E',
    maps: G('Bahnhof Vöcklamarkt Atterseebahn'),
  },
  {
    id: 'hohensalzburg',
    name: 'Hohensalzburg fortress',
    emoji: '🏰',
    what: 'The great white fortress over Salzburg — funicular up, ramparts, and the whole city below.',
    more: 'The one thing every visitor to Salzburg is assumed to have seen, and it was missing from the list. All-inclusive with the funicular €19.20; basic with funicular €15.50; €14.50 if you walk up. ⚠️ THE TRAP: the fortress CLOSES AT 20:00 even though the funicular runs until 21:30, and ticket sales stop an hour before the indoor areas close. Plan around 20:00, not 21:30. Fifteen minutes from the Wals bed.',
    drive: '🚗 15 min · 7 km from Wals',
    duration: '~2–3h',
    difficulty: 'easy',
    chips: ['€19.20 all-in with funicular', 'CLOSES 20:00 — not 21:30'],
    photo:
      'data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20400%20200%22%3E%3Crect%20width%3D%22400%22%20height%3D%22200%22%20fill%3D%22%23f0e8dc%22%2F%3E%3Ctext%20x%3D%22200%22%20y%3D%22128%22%20font-size%3D%2286%22%20text-anchor%3D%22middle%22%3E%F0%9F%8F%B0%3C%2Ftext%3E%3C%2Fsvg%3E',
    maps: G('Festung Hohensalzburg Salzburg'),
  },
  {
    id: 'kaiservilla',
    name: 'Kaiservilla, Bad Ischl',
    emoji: '🏰',
    what: 'Franz Joseph’s summer villa — entry is by 45-minute guided tour only, plus a big park.',
    more: 'Twelve minutes from the Bad Goisern bed, and the best bad-weather insurance for that half of the trip. Daily 09:30–17:00, tours 09:45–16:45. Park alone €6.70 · park + villa €24 · + Marmorschlössl €30 · park + Marmorschlössl €12.70. Note the Marmorschlössl in 2026 houses a contemporary art show, not the standing photography collection.',
    drive: '🚗 12 min · 10 km from Bad Goisern',
    duration: '~2h',
    difficulty: 'flat',
    chips: ['park + villa €24', 'guided tour only', 'good wet-weather answer'],
    photo:
      'data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20400%20200%22%3E%3Crect%20width%3D%22400%22%20height%3D%22200%22%20fill%3D%22%23f0e8dc%22%2F%3E%3Ctext%20x%3D%22200%22%20y%3D%22128%22%20font-size%3D%2286%22%20text-anchor%3D%22middle%22%3E%F0%9F%8F%B0%3C%2Ftext%3E%3C%2Fsvg%3E',
    maps: G('Kaiservilla Bad Ischl'),
  },
  {
    id: 'eurothermen-ischl',
    name: 'EurothermenResort Bad Ischl — warm water at night',
    emoji: '♨️',
    what: 'Thermal pools open until midnight — the only genuinely late option in the Salzkammergut.',
    more: 'Fifteen minutes from the Bad Goisern bed and open to midnight, with swimming ending 23:30. From €34 for a day ticket or €31.50 for four hours — pricing is dynamic, so “from” is doing real work there. The sauna world is textile-free; the pool hall is not, so you can stay in a swimsuit and skip the sauna side entirely.',
    drive: '🚗 12 min · 10 km from Bad Goisern',
    duration: '2–4h evening',
    difficulty: 'flat',
    chips: ['from €34 day · €31.50 for 4h', 'open to midnight', 'pool hall is swimsuit'],
    photo:
      'data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20400%20200%22%3E%3Crect%20width%3D%22400%22%20height%3D%22200%22%20fill%3D%22%23dfeef0%22%2F%3E%3Ctext%20x%3D%22200%22%20y%3D%22128%22%20font-size%3D%2286%22%20text-anchor%3D%22middle%22%3E%F0%9F%8F%8A%3C%2Ftext%3E%3C%2Fsvg%3E',
    swim: true,
    maps: G('EurothermenResort Bad Ischl'),
  },
  {
    id: 'fortress-concert',
    name: 'Mozart in the fortress — Golden Hall',
    emoji: '🎻',
    what: 'A chamber concert in the Golden Hall of Hohensalzburg, 20:00, with the funicular thrown in.',
    more: 'Runs EVERY NIGHT 24-31 July at 20:00 in the Goldener Saal of Hohensalzburg, so it is available any night of your week — you pick which. Roughly EUR 40-60 by category; a dinner-and-concert package exists separately. THE MOVE THAT MAKES IT WORTH IT: fortress admission and the funicular are FREE from 19:00, and the fortress closes to ordinary visitors at 20:00 — so go up at seven, have the ramparts and the city below you as it empties, then the concert. No climb, no parking war. WHAT IT COSTS YOU, NIGHT BY NIGHT: Sun 26 - hardest. You are moving to Zell with a 17:00-18:00 check-in and Salzburg is 1h20 from there; you would land back near midnight on a day you already drove. Mon 27 - 1h20 each way from Zell, home about 23:00, and it costs you the Zeller See sunset cruise, which only runs that night. Tue 28 - the sweet spot from a distance nobody minds: you are moving to Gosau anyway, Salzburg is 55 min from there, so check in, drive over, concert, back by about 22:30. Wed 29 - 55 min each way from Gosau, but Wednesday is forecast the CLEAREST day of the week, and spending its golden hour in a car is the one real waste on this list. Thu 30 - easiest by a mile: you sleep 15 minutes away in Wals. The catch is that it is also the Koenigssee day and the 20:45 Rossfeld sunset, and you are up at 05:30 the next morning. Concert or Rossfeld, not both.',

    drive: '🚗 15 min from Wals · 55 min from Gosau · 1h20 from Zell',
    duration: '~1h concert + the hour before in the fortress',
    difficulty: 'flat',
    chips: [
      '~€40–60',
      'nightly 20:00, 24–31 Jul',
      'funicular + fortress FREE from 19:00',
      'clashes with the Rossfeld sunset',
    ],
    photo:
      'data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20400%20200%22%3E%3Crect%20width%3D%22400%22%20height%3D%22200%22%20fill%3D%22%23efe7f2%22%2F%3E%3Ctext%20x%3D%22200%22%20y%3D%22128%22%20font-size%3D%2286%22%20text-anchor%3D%22middle%22%3E%F0%9F%8E%BB%3C%2Ftext%3E%3C%2Fsvg%3E',
    star: true,
    maps: G('Festung Hohensalzburg Salzburg'),
  },
];

export const byId = new Map(ACTIVITIES.map((a) => [a.id, a]));

// Official / best-explainer website per activity (her ask Jul 17: each ranked
// item links out to a page that explains and shows the place). Domain-level
// where a deep link could rot; all render as "↗ Website" on plan + rank.
export const SITES: Record<string, string> = {
  mauthausen: 'https://www.mauthausen-memorial.org/en',
  ebensee: 'https://www.memorial-ebensee.at',
  'salzburg-jewish-walk': 'https://www.stolpersteine-salzburg.at/en/the_project/',
  'jewish-ischl':
    'https://www.salzkammergut-2024.at/en/projekte/pins-of-remembrance-remembrance-culture-bad-ischl/',
  'krimml-apc': 'https://www.krimmler-wasserfaelle.at',
  kitzsteinhorn: 'https://www.kitzsteinhorn.at/en',
  schmittenhoehe: 'https://www.schmitten.at/en',
  mooserboden: 'https://www.zellamsee-kaprun.com/en',
  'zell-cruise': 'https://www.schmitten.at/en',
  'strandbad-zell': 'https://www.zellamsee-kaprun.com/en',
  'sigmund-thun': 'https://www.zellamsee-kaprun.com/en',
  baumzipfelweg: 'https://www.saalbach.com/en',
  grossglockner: 'https://www.grossglockner.at/en',
  gosausee: 'https://www.salzkammergut.at/en',
  gosaukammbahn: 'https://www.salzkammergut.at/en',
  krippenstein: 'https://dachstein-salzkammergut.com/en/',
  hallstatt: 'https://www.hallstatt.net',
  langbathsee: 'https://www.salzkammergut.at/en',
  almsee: 'https://www.salzkammergut.at/en',
  schafberg: 'https://www.schafbergbahn.at/en',
  katrin: 'https://www.katrinseilbahn.com',
  koenigssee: 'https://www.seenschifffahrt.de/en/koenigssee/',
  rossfeld: 'https://www.rossfeldpanoramastrasse.de',
  'hintersee-ramsau': 'https://www.berchtesgaden.de/en',
  chiemsee: 'https://www.chiemsee-schifffahrt.de',
  'eagles-nest': 'https://www.kehlsteinhaus.de/english/',
  untersberg: 'https://www.untersbergbahn.at',
  hellbrunn: 'https://www.hellbrunn.at/en/',
  moenchsberg: 'https://www.salzburg.info/en',
  mirabell: 'https://www.salzburg.info/en',
  golling: 'https://www.salzburgerland.com/en/',
  'gosausee-boats': 'https://gosausee-boote.at/en/',
  'grundlsee-3lakes': 'https://schifffahrt-grundlsee.at/en/3-lakes-tour',
  'tauern-spa': 'https://www.tauernspakaprun.com/en/spa/price-opening-hours',
  'wolfgangsee-eboat': 'https://www.wassersport-engel.at/elektroboote/',
  'hallstatt-sup':
    'https://www.hallstatt.net/about-hallstatt/active-summer-holiday/stand-up-paddling-in-the-salzkammergut/sup-stand-up-paddling-on-lake-hallstatt/',
};

// ---- Day-by-day menu -------------------------------------------------------
export interface PlanDay {
  id: string;
  date: string;
  title: string;
  kicker: string;
  photo: string;
  intro: string;
  activityIds: string[];
  note?: string;
}

export const DAYS: PlanDay[] = [
  {
    id: 'fri24',
    date: 'Fri Jul 24',
    title: 'The Jewish day — 4 routes',
    kicker: 'land 07:50 · realistically driving ~09:45 · candles 20:32',
    photo: P('Wiener%20Graben%20quarry%20by%20Stefanie%20J%20Steindl%20012.jpg'),
    intro:
      'One meaningful anchor before Shabbat. Pick by energy after the night flight — A is the biggest, C the softest. Every route ends with the MANDATORY grocery stop (Spar Bad Ischl ~40 min — shops close Sat AND Sun) and hours of margin before candle-lighting in Bad Goisern.',
    activityIds: ['mauthausen', 'ebensee', 'salzburg-jewish-walk', 'jewish-ischl'],
    note: 'Combo route: short Salzburg walk + Ebensee on the drive east (~40 min extra driving).',
  },
  {
    id: 'shabbat',
    date: 'Fri eve → Sat night',
    title: 'Shabbat in Bad Goisern 🕯️',
    kicker: 'candles 20:32 · ends ~21:45 Sat',
    photo: P('Shabbat%20Candles.jpg'),
    intro:
      'You’re chilling. Your own setup, frozen mains from home, naps, riverside strolls in walking distance, one of the latest Shabbatot of the year. No driving, no boats, nothing to pay at a gate — which rules out almost everything else on this site, because nearly all of it is one of those three. What is genuinely left: the riverside walk from the door, the lakeshore if you feel like the distance, and the swim marathon happening about 3 km along that shore — visible from the public bank, though the lido itself charges. The village Parkbad is a 500 m walk but takes €8.70 at the gate, so it is a Sunday thing, not a Shabbat thing.',
    activityIds: [],
  },
  {
    id: 'sun26',
    date: 'Sun Jul 26',
    title: 'Go BIG — car in hand, ends in Zell',
    kicker: 'full day · check-in der Sonnberg 17:00–18:00 · Esplanade sunset 20:53',
    photo: P('Wolfgangsee%20mit%20St.%20Wolfgang.jpg'),
    intro:
      'A full incredible day that happens to end at a new base. Three big shapes: the Grossglockner glacier drive (ends right by Zell), the Schafberg steam train + Wolfgangsee swim, or 5 Fingers at opening before the crowds + a lake afternoon. Quiet fallbacks if weather turns: Ebensee memorial, Jewish Ischl walk, Langbathsee.',
    activityIds: [
      'grossglockner',
      'schafberg',
      'wolfgangsee-eboat',
      'krippenstein',
      'ebensee',
      'jewish-ischl',
      'langbathsee',
      'strandbad-untersee',
      'hallstattersee-boat',
      'pathfinder-kayak',
      'hallstatt-by-train',
      'parkbad-goisern',
      'fortress-concert',
    ],
    note: 'If Schafberg is your Sunday pick — RESERVE the train online a few days ahead; July seats genuinely sell out. Grossglockner and Krippenstein are clear-weather picks: check the forecast/webcams that morning and swap freely.',
  },
  {
    id: 'mon27',
    date: 'Mon Jul 27',
    title: 'Full Zell day — pick ONE anchor',
    kicker: 'evening: ⭐ sunset cruise + Strandbad swim',
    photo: P('Kitzsteinhorn3.jpg'),
    intro:
      'One anchor + water + the boat at night. The glacier for the wow, Krimml for falls + the 1947 exodus memorial, Schmittenhöhe for the easy panorama, Mooserboden for the high dams. Evening is the Zeller See sunset cruise — your Montenegro boat-evening, Austrian edition.',
    activityIds: [
      'kitzsteinhorn',
      'krimml-apc',
      'schmittenhoehe',
      'mooserboden',
      'zell-cruise',
      'strandbad-zell',
      'tauern-spa',
      'sigmund-thun',
      'baumzipfelweg',
      'frost-rafting',
      'taxenbach-rafting',
      'out2-rafting',
      'lofer-basecamp',
      'kitzlochklamm',
      'pinzgauer-bahn',
      'seisenbergklamm',
      'fortress-concert',
    ],
  },
  {
    id: 'tue28',
    date: 'Tue Jul 28',
    title: 'Move to Gosau → the mirror lake',
    kicker: '1h25 via Bad Ischl · check-in 16:00+ · Gosausee sunset ~20:51',
    photo: P('Vorderer%20Gosausee%204.jpg'),
    intro:
      'Slow Zell morning (last swim), Bad Ischl on the way (Spar restock, café, optional Jewish Ischl walk or Katrin cable car), check in at Transylvania Villa, then the evening mirror-lake loop when the buses are gone. The “we’re really here” moment.',
    activityIds: [
      'jewish-ischl',
      'katrin',
      'gosausee',
      'gosausee-boats',
      'liechtensteinklamm',
      'kaiservilla',
      'eurothermen-ischl',
      'fortress-concert',
    ],
  },
  {
    id: 'wed29',
    date: 'Wed Jul 29',
    title: 'Platforms, villages, or Bavaria',
    kicker: 'full Gosau day · sunset back at the Gosausee',
    photo: P('A-Krippenstein-5fingers.jpg'),
    intro:
      '5 Fingers if Sunday didn’t take it, Hallstatt the quiet way (early + boat), the Bavaria mirror trio (Hintersee + Zauberwald + Ramsau church), the Gosaukamm cable car above your own lake, or the quietest lakes. If Friday went to Salzburg, Mauthausen fits here (1h40 each way).',
    activityIds: [
      'krippenstein',
      'hallstatt',
      'hintersee-ramsau',
      'grundlsee-3lakes',
      'hallstatt-sup',
      'gosaukammbahn',
      'langbathsee',
      'mauthausen',
      'dachstein-icecave',
      'salzwelten-altaussee',
      'attersee-bahn-schiff',
      'fortress-concert',
    ],
  },
  {
    id: 'thu30',
    date: 'Thu Jul 30',
    title: '⭐ The Königssee signature day',
    kicker: 'checkout Gosau ~08:30 → boat by 10:30 → Rossfeld sunset → sleep in Wals',
    photo: P('K%C3%B6nigssee%20St.%20Bartholom%C3%A4%2002.jpg'),
    intro:
      'The one to protect. Silent boat under the Watzmann, the echo trumpet, St. Bartholomä, the flat walk to the Obersee mirror. Luggage rides in the car — no backtracking. Sunset from the Rossfeld ridge road (zero walking), then 30 min to the airport hotel. Swaps: Chiemsee island-boat day, or an easy Salzburg afternoon (Mönchsberg, Mirabell, Hellbrunn, Untersberg).',
    activityIds: [
      'koenigssee',
      'rossfeld',
      'chiemsee',
      'untersberg',
      'moenchsberg',
      'mirabell',
      'hellbrunn',
      'eagles-nest',
      'golling',
      'hohensalzburg',
      'fortress-concert',
    ],
  },
  {
    id: 'fri31',
    date: 'Fri Jul 31',
    title: 'Home 🛫',
    kicker: 'wake 05:30 · drop car 06:30 · LY5194 09:55 → TLV 13:25',
    photo: P('El%20Al%20B787-9%20%284X-EDH%29%20%40%20SFO%2C%20Nov%202019.jpg'),
    intro:
      'Checkout works from 06:00; key-drop for the car (photos first — counter opens 08:00). Home with the whole Friday afternoon to reset before Shabbat.',
    activityIds: [],
  },
];

// ---- Ranking page inputs ---------------------------------------------------
// Must-do candidates: the lifetime-memory pool both of them rank.
export const MUST_DO_IDS: string[] = [
  'koenigssee',
  'gosausee-boats',
  'grundlsee-3lakes',
  'gosausee',
  'kitzsteinhorn',
  'zell-cruise',
  'krimml-apc',
  'krippenstein',
  'grossglockner',
  'schafberg',
  'mauthausen',
  'ebensee',
  'hallstatt',
  'hintersee-ramsau',
  'chiemsee',
  'mooserboden',
];

// Best-sunset board: spot + when + why, each tied to an activity where useful.
export interface SunsetSpot {
  id: string;
  name: string;
  night: string;
  time: string;
  why: string;
  drive: string; // distance rule applies here too
  photo: string;
}

export const SUNSETS: SunsetSpot[] = [
  {
    id: 'sunset-goisern',
    name: 'Bad Goisern valley (Shabbat)',
    night: 'Fri + Sat',
    time: '~20:50',
    why: 'Walking-distance riverside — the Shabbat-legal sunset. Slow gold over the valley walls.',
    drive: '🚗 0 — on foot from the apartment',
    photo: P('Bad%20Goisern%20-%20Ortsansicht%20%28a%29.JPG'),
  },
  {
    id: 'sunset-esplanade',
    name: 'Zeller See Esplanade',
    night: 'Sun',
    time: '20:53',
    why: 'First night at the lake — the classic promenade view as the peaks go pink.',
    drive: '🚗 0 — 15 min walk down from der Sonnberg',
    photo: P(
      '2017-07-21%20%28177%29%20Beach%20promenade%20at%20Zeller%20See%2C%20Zell%20am%20See%2C%20Austria.jpg',
    ),
  },
  {
    id: 'sunset-cruise',
    name: 'ON the Zeller See (boat)',
    night: 'Mon',
    time: '~20:00 boarding',
    why: 'The sunset cruise — gold light FROM the water. Likely lifetime memory.',
    drive: '🚗 0 — Esplanade pier',
    photo: P('20190624.Zell%20am%20See.-014.jpg'),
  },
  {
    id: 'sunset-gosausee',
    name: 'Vorderer Gosausee',
    night: 'Tue + Wed',
    time: '~20:51',
    why: 'The Dachstein doubled in still water, nearly alone after the buses leave. The trip’s postcard.',
    drive: '🚗 14 min · 9 km from the Gosau apartment',
    photo: P('Vorderer%20Gosausee%204.jpg'),
  },
  {
    id: 'sunset-hallstatt-shore',
    name: 'Hallstättersee west shore',
    night: 'Wed (alt)',
    time: '~20:50',
    why: 'Across the water from Hallstatt village as its lights come on — quiet pullouts along the road.',
    drive: '🚗 20 min · 15 km from Gosau',
    photo: P('Marktplatz%2C%20Hallstatt%2C%2017.05.2019.jpg'),
  },
  {
    id: 'sunset-rossfeld',
    name: 'Rossfeld ridge road',
    night: 'Thu',
    time: '~20:45',
    why: 'Drive to 1,560 m, step out, watch the sun set over two countries. Zero walking.',
    drive: '🚗 30 min · 26 km from Wals (24 min from the Königssee)',
    photo: P('Kehlsteinhaus%202.jpg'),
  },
  {
    id: 'sunset-moenchsberg',
    name: 'Mönchsberg over Salzburg',
    night: 'Thu (alt)',
    time: '20:47',
    why: 'The old city going gold under the fortress — the urban-romantic alternative.',
    drive: '🚗 15 min · 8 km from Wals + stone stairs or €3 lift',
    photo: P('Salzburg%20Altstadt%20Panorama%20' + '20170409%2002.jpg'),
  },
  {
    id: 'sunset-hintersee',
    name: 'Hintersee mirror (Bavaria)',
    night: 'Wed (alt)',
    time: '~20:48',
    why: 'The Hochkalter reflected at dusk — stillest water of the trip.',
    drive: '🚗 1h17 · 78 km from Gosau',
    photo: P('Hintersee-Hochkalter.jpg'),
  },
];

export const BUILD_STAMP = '2026-07-17 19:45';
