// GENERATED by scripts/gen-table-data.mjs — do not hand-edit.
// Drive minutes: Google Distance Matrix (driving), pulled 2026-07-23, from each
// booked bed. "near" is STRAIGHT-LINE km from Google geocoding, same day — it
// answers "what else is right there", not "how long is the drive".
// Regenerate with: node scripts/gen-table-data.mjs

export interface TableBase {
  key: string;
  name: string;
}

export interface NearRef {
  id: string;
  km: number;
}

export interface TableRow {
  id: string;
  /** Drive minutes from each base, in BASE_ORDER order. */
  fromBase: number[];
  /** Top 2 things that make it unique. */
  unique: string[];
  /** One line: why do it. */
  why: string;
  /** The two closest other stops, straight-line. */
  near: NearRef[];
}

export const BASE_ORDER: TableBase[] = [
  {
    key: 'goisern',
    name: 'Bad Goisern',
  },
  {
    key: 'zell',
    name: 'Zell am See',
  },
  {
    key: 'gosau',
    name: 'Gosau',
  },
  {
    key: 'wals',
    name: 'Wals',
  },
];

export const TABLE_ROWS: Record<string, TableRow> = {
  mauthausen: {
    id: 'mauthausen',
    fromBase: [103, 170, 120, 104],
    unique: ['The quarry and its “Stairs of Death”', 'The Room of Names — free entry, audio guide'],
    why: 'The one unmissable act of remembrance on this trip, and the reason Friday exists.',
    near: [
      {
        id: 'almsee',
        km: 68.9,
      },
      {
        id: 'ebensee',
        km: 73.3,
      },
    ],
  },
  ebensee: {
    id: 'ebensee',
    fromBase: [25, 127, 42, 70],
    unique: ['You walk INTO the tunnel prisoners dug', '8°C inside, in July'],
    why: 'The heaviest history of the week is 25 minutes from your first bed — no day lost to it.',
    near: [
      {
        id: 'langbathsee',
        km: 7.2,
      },
      {
        id: 'almsee',
        km: 14.9,
      },
    ],
  },
  'salzburg-jewish-walk': {
    id: 'salzburg-jewish-walk',
    fromBase: [67, 83, 58, 19],
    unique: ['Stolpersteine set into the pavement', 'The Marko Feingold bridge + a living shul'],
    why: 'Flat, free and self-paced — the meaningful option on a day with no energy for a drive.',
    near: [
      {
        id: 'moenchsberg',
        km: 0.6,
      },
      {
        id: 'mirabell',
        km: 0.6,
      },
    ],
  },
  'jewish-ischl': {
    id: 'jewish-ischl',
    fromBase: [12, 114, 29, 58],
    unique: ['The Pins of Remembrance route', 'An imperial spa town that had a real community'],
    why: 'An hour of meaning attached to a stop you are making anyway for groceries.',
    near: [
      {
        id: 'katrin',
        km: 1.8,
      },
      {
        id: 'hallstatt-sup',
        km: 13.8,
      },
    ],
  },
  'krimml-apc': {
    id: 'krimml-apc',
    fromBase: [156, 60, 137, 126],
    unique: [
      'Austria’s highest waterfall, 380 m',
      'The 1947 Jewish exodus over the Krimmler Tauern',
    ],
    why: 'Water and Jewish history in one walk — uphill but easy, and worth the drive from Zell.',
    near: [
      {
        id: 'baumzipfelweg',
        km: 31.2,
      },
      {
        id: 'mooserboden',
        km: 41.9,
      },
    ],
  },
  kitzsteinhorn: {
    id: 'kitzsteinhorn',
    fromBase: [107, 12, 88, 77],
    unique: ['Real glacier snow underfoot in July', 'Platform straight into the Hohe Tauern'],
    why: '3,029 m without a single step of climbing — three lifts do all of it.',
    near: [
      {
        id: 'tauern-spa',
        km: 1,
      },
      {
        id: 'sigmund-thun',
        km: 2.2,
      },
    ],
  },
  schmittenhoehe: {
    id: 'schmittenhoehe',
    fromBase: [109, 4, 90, 74],
    unique: ['The easiest big view of the trip', 'Zell’s own mountain, gondola from town'],
    why: 'When you want the panorama but not the glacier day, this is the 36-euro version.',
    near: [
      {
        id: 'zell-cruise',
        km: 2,
      },
      {
        id: 'strandbad-zell',
        km: 2.1,
      },
    ],
  },
  mooserboden: {
    id: 'mooserboden',
    fromBase: [118, 22, 100, 88],
    unique: ['Two turquoise reservoirs at 2,040 m', 'Buses + funicular do the climbing'],
    why: 'Flat dam walks with glaciers on three sides — big scenery, no effort.',
    near: [
      {
        id: 'sigmund-thun',
        km: 4.9,
      },
      {
        id: 'kitzsteinhorn',
        km: 6.8,
      },
    ],
  },
  'zell-cruise': {
    id: 'zell-cruise',
    fromBase: [106, 3, 87, 73],
    unique: ['Gold light FROM the water', 'Monday evening is the window'],
    why: 'Your Montenegro boat-evening, Austrian edition — the likeliest lifetime memory of the week.',
    near: [
      {
        id: 'strandbad-zell',
        km: 0.7,
      },
      {
        id: 'schmittenhoehe',
        km: 2,
      },
    ],
  },
  'strandbad-zell': {
    id: 'strandbad-zell',
    fromBase: [107, 2, 88, 71],
    unique: ['Swim off decks into open lake', 'A 2-minute walk from the Zell bed'],
    why: 'The cheapest good hour of the trip, and the reason to keep a suit in the day bag.',
    near: [
      {
        id: 'zell-cruise',
        km: 0.7,
      },
      {
        id: 'schmittenhoehe',
        km: 2.1,
      },
    ],
  },
  'sigmund-thun': {
    id: 'sigmund-thun',
    fromBase: [111, 15, 93, 81],
    unique: ['Boardwalk hung over glacier water', 'Ends at a small reservoir loop'],
    why: 'An hour, €3.50, and cool air — the perfect filler on a hot Zell afternoon.',
    near: [
      {
        id: 'kitzsteinhorn',
        km: 2.2,
      },
      {
        id: 'tauern-spa',
        km: 3.1,
      },
    ],
  },
  baumzipfelweg: {
    id: 'baumzipfelweg',
    fromBase: [138, 36, 119, 97],
    unique: ['A path through the treetops', 'The “Golden Gate of the Alps” suspension bridge'],
    why: 'Ramps, no steps — the walk that feels adventurous without being one.',
    near: [
      {
        id: 'schmittenhoehe',
        km: 20.3,
      },
      {
        id: 'sigmund-thun',
        km: 21,
      },
    ],
  },
  grossglockner: {
    id: 'grossglockner',
    fromBase: [113, 24, 95, 83],
    unique: ['Austria’s great alpine road, 2,504 m', 'Marmots and glacier views from the car'],
    why: 'The whole day happens through the windscreen — and it ends right at your Zell bed.',
    near: [
      {
        id: 'mooserboden',
        km: 8.8,
      },
      {
        id: 'sigmund-thun',
        km: 12.2,
      },
    ],
  },
  gosausee: {
    id: 'gosausee',
    fromBase: [33, 100, 15, 65],
    unique: ['The Dachstein doubled in still water', 'Flat 1-hour gravel circle'],
    why: 'The trip’s postcard, and you sleep 15 minutes away — go once the buses leave.',
    near: [
      {
        id: 'gosausee-boats',
        km: 0,
      },
      {
        id: 'gosaukammbahn',
        km: 0.9,
      },
    ],
  },
  'gosausee-boats': {
    id: 'gosausee-boats',
    fromBase: [33, 100, 15, 65],
    unique: ['Float inside the Dachstein reflection', 'E-boat €26/h · SUP €17/h, walk-up'],
    why: 'You are going to the lake anyway; this puts you ON the mirror instead of beside it.',
    near: [
      {
        id: 'gosausee',
        km: 0,
      },
      {
        id: 'gosaukammbahn',
        km: 0.9,
      },
    ],
  },
  krippenstein: {
    id: 'krippenstein',
    fromBase: [22, 109, 24, 74],
    unique: ['5 Fingers hangs over a 400 m drop', 'Gondola to 2,109 m, then an easy stroll'],
    why: 'The most dramatic photo of the week — but only book it on a clear morning.',
    near: [
      {
        id: 'hallstatt',
        km: 4.5,
      },
      {
        id: 'hallstatt-sup',
        km: 6,
      },
    ],
  },
  hallstatt: {
    id: 'hallstatt',
    fromBase: [18, 106, 21, 70],
    unique: ['A 7,000-year-old salt village on the lake', 'See it from a small electric boat'],
    why: 'The place everyone comes for — do it before 09:30 or after 17:00 and it is yours.',
    near: [
      {
        id: 'hallstatt-sup',
        km: 3.2,
      },
      {
        id: 'krippenstein',
        km: 4.5,
      },
    ],
  },
  gosaukammbahn: {
    id: 'gosaukammbahn',
    fromBase: [27, 94, 9, 59],
    unique: ['Cable car above your own lake', 'Green plateau facing the Dachstein wall'],
    why: 'Nine minutes from the Gosau bed — the low-effort half-day when you want a mountain.',
    near: [
      {
        id: 'gosausee',
        km: 0.9,
      },
      {
        id: 'gosausee-boats',
        km: 0.9,
      },
    ],
  },
  langbathsee: {
    id: 'langbathsee',
    fromBase: [37, 139, 54, 82],
    unique: ['A forest lake almost nobody is at', 'Flat 1-hour shore loop, swimmable'],
    why: 'The quiet, free alternative when Hallstatt feels like too many people.',
    near: [
      {
        id: 'ebensee',
        km: 7.2,
      },
      {
        id: 'jewish-ischl',
        km: 14.3,
      },
    ],
  },
  almsee: {
    id: 'almsee',
    fromBase: [74, 154, 91, 87],
    unique: ['The quietest water of the trip', 'Herons, a 1h45 flat loop, no crowds'],
    why: 'If a day needs to be about nothing at all, this is where you spend it.',
    near: [
      {
        id: 'ebensee',
        km: 14.9,
      },
      {
        id: 'grundlsee-3lakes',
        km: 17.4,
      },
    ],
  },
  schafberg: {
    id: 'schafberg',
    fromBase: [28, 118, 45, 57],
    unique: ['A 130-year-old steam cog railway', 'Three lakes from 1,783 m'],
    why: 'The romance option — but RESERVE, and pick your downhill slot when you book.',
    near: [
      {
        id: 'wolfgangsee-eboat',
        km: 6.1,
      },
      {
        id: 'katrin',
        km: 13.4,
      },
    ],
  },
  katrin: {
    id: 'katrin',
    fromBase: [14, 116, 31, 62],
    unique: ['Bad Ischl’s own small, uncrowded lift', 'Gentle ridge paths over the Salzkammergut'],
    why: 'Fifteen minutes from the first bed, and the local one rather than the famous one.',
    near: [
      {
        id: 'jewish-ischl',
        km: 1.8,
      },
      {
        id: 'hallstatt-sup',
        km: 12.6,
      },
    ],
  },
  koenigssee: {
    id: 'koenigssee',
    fromBase: [87, 78, 68, 33],
    unique: ['Silent electric boats + the echo trumpet', 'Flat 15-min walk to the Obersee mirror'],
    why: 'The signature day. Be at the dock by 10:30 — queues and the calmest water are both then.',
    near: [
      {
        id: 'eagles-nest',
        km: 9.8,
      },
      {
        id: 'hintersee-ramsau',
        km: 11,
      },
    ],
  },
  rossfeld: {
    id: 'rossfeld',
    fromBase: [81, 86, 62, 35],
    unique: ['Drive to 1,560 m — zero walking', 'Sunset over two countries'],
    why: 'The best sunset of the trip costs €9.50 and no steps, 30 minutes from the last bed.',
    near: [
      {
        id: 'eagles-nest',
        km: 3.9,
      },
      {
        id: 'golling',
        km: 4.4,
      },
    ],
  },
  'hintersee-ramsau': {
    id: 'hintersee-ramsau',
    fromBase: [97, 67, 78, 36],
    unique: ['The stillest water of the trip', 'The mossy “enchanted forest” boulder path'],
    why: 'Rowboats, flat paths and Germany’s most-photographed church view, all in one stop.',
    near: [
      {
        id: 'koenigssee',
        km: 11,
      },
      {
        id: 'eagles-nest',
        km: 14.3,
      },
    ],
  },
  chiemsee: {
    id: 'chiemsee',
    fromBase: [108, 101, 90, 45],
    unique: ['Steamer to Ludwig II’s unfinished Versailles', 'A car-free nuns’ island'],
    why: 'The gentlest big day — but it needs a whole day, so only if one frees up.',
    near: [
      {
        id: 'hintersee-ramsau',
        km: 46.1,
      },
      {
        id: 'moenchsberg',
        km: 50.7,
      },
    ],
  },
  'eagles-nest': {
    id: 'eagles-nest',
    fromBase: [78, 81, 60, 29],
    unique: [
      'Special bus + a brass elevator into the rock',
      'Hitler’s mountaintop house, now a viewpoint',
    ],
    why: 'Heavy history with huge views — entirely your call whether you want it this week.',
    near: [
      {
        id: 'rossfeld',
        km: 3.9,
      },
      {
        id: 'golling',
        km: 8,
      },
    ],
  },
  'grundlsee-3lakes': {
    id: 'grundlsee-3lakes',
    fromBase: [25, 123, 38, 88],
    unique: ['A WOODEN boat up the fjord-like Toplitzsee', 'A hidden third lake at the end'],
    why: 'Sitting the whole way, 25 minutes from the first bed, and almost nobody knows it.',
    near: [
      {
        id: 'krippenstein',
        km: 12.6,
      },
      {
        id: 'hallstatt-sup',
        km: 13.7,
      },
    ],
  },
  'tauern-spa': {
    id: 'tauern-spa',
    fromBase: [107, 11, 89, 77],
    unique: ['Panoramic warm pools facing the glacier', 'Open to 21:00, evening rate ~€25.50'],
    why: 'The cozy-evening upgrade, 11 minutes from the Zell bed — perfect after a wet day.',
    near: [
      {
        id: 'kitzsteinhorn',
        km: 1,
      },
      {
        id: 'sigmund-thun',
        km: 3.1,
      },
    ],
  },
  'wolfgangsee-eboat': {
    id: 'wolfgangsee-eboat',
    fromBase: [30, 103, 47, 41],
    unique: ['A red e-boat with a sun canopy', 'Swim ladder — swim off it mid-lake'],
    why: 'No reservation, go at 10:00, and it pairs with the Schafberg on the same day.',
    near: [
      {
        id: 'schafberg',
        km: 6.1,
      },
      {
        id: 'katrin',
        km: 19.4,
      },
    ],
  },
  'hallstatt-sup': {
    id: 'hallstatt-sup',
    fromBase: [9, 96, 11, 61],
    unique: [
      'Glassy morning water on the north shore',
      'Hallstatt’s crowds 8 km away across the lake',
    ],
    why: 'Your May postcard-dream, nine minutes from the first bed — mornings are glass.',
    near: [
      {
        id: 'hallstatt',
        km: 3.2,
      },
      {
        id: 'krippenstein',
        km: 6,
      },
    ],
  },
  untersberg: {
    id: 'untersberg',
    fromBase: [65, 71, 46, 10],
    unique: ['1,776 m in 8.5 minutes', 'The big cliff face over Salzburg'],
    why: 'Ten minutes from the last bed — an alpine morning without leaving the airport hour.',
    near: [
      {
        id: 'hellbrunn',
        km: 4.3,
      },
      {
        id: 'moenchsberg',
        km: 8.2,
      },
    ],
  },
  hellbrunn: {
    id: 'hellbrunn',
    fromBase: [67, 72, 48, 13],
    unique: ['Booby-trapped 400-year-old water gardens', 'A water-powered puppet theatre'],
    why: 'The laugh-out-loud stop — shaded, silly, and 13 minutes from the last bed.',
    near: [
      {
        id: 'untersberg',
        km: 4.3,
      },
      {
        id: 'salzburg-jewish-walk',
        km: 4.3,
      },
    ],
  },
  moenchsberg: {
    id: 'moenchsberg',
    fromBase: [77, 88, 66, 21],
    unique: ['Free stone stairs (or a €3 lift)', 'Fortress one end, river and domes below'],
    why: 'Salzburg going gold from above, for free — best in the last hour of light.',
    near: [
      {
        id: 'salzburg-jewish-walk',
        km: 0.6,
      },
      {
        id: 'mirabell',
        km: 0.7,
      },
    ],
  },
  mirabell: {
    id: 'mirabell',
    fromBase: [64, 85, 60, 17],
    unique: ['The exact framed fortress view', 'The Sound of Music steps + dwarf garden'],
    why: 'Free, flat, 45 minutes — the one that fits into any leftover gap.',
    near: [
      {
        id: 'salzburg-jewish-walk',
        km: 0.6,
      },
      {
        id: 'moenchsberg',
        km: 0.7,
      },
    ],
  },
  golling: {
    id: 'golling',
    fromBase: [56, 65, 37, 25],
    unique: ['A fairy-tale double drop', '15 minutes of easy forest path'],
    why: 'Maximum wow per step of anything on this list — about an hour, all in.',
    near: [
      {
        id: 'rossfeld',
        km: 4.4,
      },
      {
        id: 'eagles-nest',
        km: 8,
      },
    ],
  },
};
